<a href="https://colab.research.google.com/github/KushGabani/Lab-Assignments/blob/main/Python_Practical_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from collections import Counter
# Assignment 1
a1q1_input = "King Arthur"
print("Q1. Input : 'King Arthur' ")
print("    Output : " + a1q1_input[::-1])

print()

a1q2_input = "Chocolate Cookie"
print("Q2. Input : 'Chocolate Cookie")
print("    Output : " + a1q2_input.split()[-1])
print("    Output : " + a1q2_input.replace("Chocolate", "Vanila"))

print()

a1q3_input = "Welcome to the world of python"
print("Q3. Input : 'Welcome to the world of python")
print("    Output : " + a1q3_input[::3])

print()

a1q4_input = """Apple Inc. is an American multinational technology company headquartered in Cupertino, California, that designs, develops, and sells consumer electronics, computer software, andonline services. It is considered one of the Big Four of technology along with Amazon, Google, and Facebook. The company's hardware products include the iPhone smartphone, theiPad tablet computer, the Mac personal computer, the iPod portable media player, the AppleWatch smartwatch, the Apple TV digital media player, the Apple AirPods wireless earbudsand the HomePod smart speaker. Apple's software includes the macOS, iOS, iPadOS, watchOS and tvOS operating systems, the iTunes media player, the Safari web browser, andthe iLife and iWork creativity and productivity suites, as well as professional applicationslike Final Cut Pro, Logic Pro, and Xcode. Its online services include the iTunes Store, theiOS App Store, Mac App Store, Apple Music, Apple TV+, iMessage, and iCloud. Otherservices include Apple Store, Genius Bar, AppleCare, Apple Pay, Apple Pay Cash, andApple Card. Apple was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne inApril
1976 to develop and sell Wozniak's Apple I personal computer, though Wayne sold his shareback within 12 days. It was incorporated as Apple Computer, Inc. 
"""

print()

print("Q4. Count and print the occurence of word 'Apple'.")
print("    Output : Count of 'Apple' : " + str(dict(Counter(a1q4_input.split()))['Apple']))
a1q4_input = a1q4_input.replace("Apple", "Google")
print("    Output : Replace 'Apple' with 'Google'...done")
print("    Output : Position of the word TV : " + str(a1q4_input.find("TV")))

print()

a1q5_input = "From pritirad@gmail.com Sun Oct 16 20:29:16"
print("Q5. Input : " + a1q5_input)
print("    Output : this email has been sent through " + a1q5_input.split("@")[-1].split()[0] + ". It was send on " + " ".join(a1q5_input.split("@")[-1].split()[1:]))

print()

a1q6_input = "Violet Indigo Blue Green Yelllow Orange Red"
print("Q6. Input : " + a1q6_input)
print("    Output : " + "".join([color[0] for color in a1q6_input.split()]))

print()

a1q7_input = "TechBeamers"
print("Q7. Input : Switches cases for 'TechBeamers'")
print("    Output : " + a1q7_input.swapcase())

print()

a1q8_input = "This is a good example"
print("Q8. Input : 'This is a good example' to ['This', 'is', 'a', 'good', 'example']")
print("    Output : " + str(a1q8_input.split()))

print()

a1q9_input = "A paragraph is a series of sentences that are organized and coherent, and are all relatedtoasingle topic. Almost every piece of writing you do that is longer than a fewsentences shouldbe organized into paragraphs."
print("Q9. Input : Split the paragraph into four parts and count length of each statement.")
sent = []
sent.extend(a1q9_input.split(".")[:-1])
sent.extend(a1q9_input.split(".")[0].split(","))
sent = sent[1:]
print("    Output : " + str([len(s) for s in sent]))

Q1. Input : 'King Arthur' 
    Output : ruhtrA gniK

Q2. Input : 'Chocolate Cookie
    Output : Cookie
    Output : Vanila Cookie

Q3. Input : 'Welcome to the world of python
    Output : Wceohwloph


Q4. Count and print the occurence of word 'Apple'.
    Output : Count of 'Apple' : 11
    Output : Replace 'Apple' with 'Google'...done
    Output : Position of the word TV : 473

Q5. Input : From pritirad@gmail.com Sun Oct 16 20:29:16
    Output : this email has been sent through gmail.com. It was send on Sun Oct 16 20:29:16

Q6. Input : Violet Indigo Blue Green Yelllow Orange Red
    Output : VIBGYOR

Q7. Input : Switches cases for 'TechBeamers'
    Output : tECHbEAMERS

Q8. Input : 'This is a good example' to ['This', 'is', 'a', 'good', 'example']
    Output : ['This', 'is', 'a', 'good', 'example']

Q9. Input : Split the paragraph into four parts and count length of each statement.
    Output : [107, 68, 35]


In [ ]:
import keyword
#Assignment 2
a2q1_input = "this is a sample sentence"
print("Q1. Input: Count and sort all the words of sentences in descending order.")
print("    Output : number of words in the sentence " + str(len(a2q1_input.split())) + ", words sorted in descending order are : " + str(sorted(a2q1_input.split(),reverse = True)))

print()

a2q2_input = [10, 2, 35, 5]
print("Q2. Input : Sum all the items in a list.")
print("     Output : ", sum(a2q2_input))

print()

a2q3_input = ["hi", "how", "are", "you"]
a2q3_input.sort()
find = input("Enter the word you want to get position of : ")
print("Q3. Input : Arrange list in ascending order and find positions of a specific word")
print("    Output : Sorted order - " + str(a2q3_input) + "\t position - " + str(a2q3_input.index(find)))

print()

dictionary = ["how", "are", "you", "I", "am", "were", "was", "will"]
a2q4_input = "hi how are u"
print("Q4. Input : Find dictionary and non-dictionary words in the sentence.")
print("    Output : Dictionary words - " + str([word for word in a2q4_input.split() if word in dictionary]) + "\t Non-dictionary words - "  + str([word for word in a2q4_input.split() if word not in dictionary]))

print()

a2q5_input = ["for", "hi"]
print("Q5. Input : A given string is a keyword or not.")
print("    Output : keywords - " + str([word for word in a2q5_input if keyword.iskeyword(word)]) + "\t not a keyword - " + str([word for word in a2q5_input if not keyword.iskeyword(word)]))

Q1. Input: Count and sort all the words of sentences in descending order.
    Output : number of words in the sentence 5, words sorted in descending order are : ['this', 'sentence', 'sample', 'is', 'a']

Q2. Input : Sum all the items in a list.
     Output :  52

Q4. Input : Find dictionary and non-dictionary words in the sentence.
    Output : Dictionary words - ['how', 'are']	 Non-dictionary words - ['hi', 'u']

Q5. Input : A given string is a keyword or not.
    Output : keywords - ['for']	 not a keyword - ['hi']


In [ ]:
# Assignment 3
a3q1_input = "this is a sample sentence."
print("Q1. Input : Count the number of words in a sentence")
print("    Output : Count - " + str(len(a3q1_input.split())))

print()

a3q2_input = { "math" : [80, 72, 69, 92, 97], "english" : [88, 68, 76, 66, 96], "computer" : [88, 75, 94, 92, 66]}
print("Q2. Input : Total marks of each subject. ")
total_marks = [sum(marks) for sub, marks in a3q2_input.items()]
print("    Output : maths : ", total_marks[0])
print("             english : ", total_marks[1])
print("             computer : ", total_marks[2])

print()

a3q3_input_a = "apple banana mango"
a3q3_input_b = "banana fruits mango"
print("Q3. Input : list out the uncommon words from two strings.")
output = [word for word in a3q3_input_a.split() if word not in a3q3_input_b.split()]
output.extend([word for word in a3q3_input_b.split() if word not in a3q3_input_a.split()])
print("    Output : Uncommon words - " + str(output))

print()

a3q4_input = "a sentence that has its own sentiments"
print("Q4. Input : Find the frequency of a substring in a string.")
print("    Output : Frequency - " + str(len([i for i in range(len(a3q4_input)) if a3q4_input.startswith("sent", i)])))

Q1. Input : Count the number of words in a sentence
    Output : Count - 5

Q2. Input : Total marks of each subject. 
    Output : maths :  410
             english :  394
             computer :  415

Q3. Input : list out the uncommon words from two strings.
    Output : Uncommon words - ['apple', 'fruits']

Q4. Input : Find the frequency of a substring in a string.
    Output : Frequency - 2


In [ ]:
# Assignment 4
a4q1_input = ["This", "is", "not", "a", "straight", "sentence"]
print("Q1. Input : Display all elements of the list in reverse.")
print("    Output : " + str(a4q1_input[::-1]))

print()

a4q2_input = [22, 54, 54, 68, 21, 9]
print("Q2. Input : Find the biggest and smallest element in the list.")
print("    Output : biggest number - " + str(max(a4q2_input)) + ", smallest number - " + str(min(a4q2_input)))

print()

a4q3_input_a = [1,2,3,4]
a4q3_input_b = ["Kush","Manav","Himanshu","Nakul"]
a4q3_input_c = [30000,55000,2100,15000]
print("Q3. Input : Sort among different lists")
print(f"    Output: Sort by employee name : {sorted(zip(a4q3_input_a, a4q3_input_b, a4q3_input_c), key=lambda x: x[1])}")
print(f"            Sort by salary : {sorted(zip(a4q3_input_a, a4q3_input_b, a4q3_input_c), key=lambda x: x[2])}")

print()

a4q4_input = {"book_1" :700,"book_2" :250,"book_3" : 400}
print("Q4. Input : Sort from high to low")
print(f"    Output : Sort from high to low : {sorted(a4q4_input.items(), key=lambda x: x[1])}")

print()

a4q5_input = {"surat" : 45, "mumbai": 22, "delhi": 35}
print("Q5. Input : Lowest, highest and average temperature : ")
print(f"    Output : Highest : {max(list(a4q5_input.values()))}\t\t Lowest : {min(list(a4q5_input.values()))}\t\t Average : Highest : {(max(list(a4q5_input.values())) + min(list(a4q5_input.values()))) / 2}")

print()

marks = 0
class1 = ''
a4q6_input = {'Maths': 90, 'Science': 80, 'English': 85, 'Computer': 80, 'Hindi': 91}
for items in a4q6_input.items():
    marks += items[1]
percent = (marks / 600) * 100
if percent >= 95:
    class1 = 'Distinction'
elif 70 <= percent <= 95:
    class1 = 'First'
elif 60 <= percent <= 70:
    class1 = 'Second'
elif 50 <= percent <= 60:
    class1 = 'Third'
elif 40 <= percent <= 50:
    class1 = 'Average'
elif 35 <= percent <= 40:
    class1 = 'Just Above'

print("Q6. Input : Display result of the student")
print("    Output : Class - " + class1)
print()


Q1. Input : Display all elements of the list in reverse.
    Output : ['sentence', 'straight', 'a', 'not', 'is', 'This']

Q2. Input : Find the biggest and smallest element in the list.
    Output : biggest number - 68, smallest number - 9

Q3. Input : Sort among different lists
    Output: Sort by employee name : [(3, 'Himanshu', 2100), (1, 'Kush', 30000), (2, 'Manav', 55000), (4, 'Nakul', 15000)]
            Sort by salary : [(3, 'Himanshu', 2100), (4, 'Nakul', 15000), (1, 'Kush', 30000), (2, 'Manav', 55000)]

Q4. Input : Sort from high to low
    Output : Sort from high to low : [('book_2', 250), ('book_3', 400), ('book_1', 700)]

Q5. Input : Lowest, highest and average temperature : 
    Output : Highest : 45		 Lowest : 22		 Average : Highest : 33.5

Q6. Input : Display result of the student
    Output : Class - First



In [ ]:
from collections import Counter
# Assignment 5
a6q1_input = [1,3,5,7,9]
print("Q1. Input: Looping through each elements in the array : ")
print("    Output: ")
for i in a6q1_input:
    print(i)
print(a6q1_input[0])
print(a6q1_input[1])
print(a6q1_input[2])

print()

print("Q2. Input: Reverse a list.")
a6q2_input = [11, 2, 323, 414, 55]
print("    Output: Reversed array - ", a6q2_input[::-1])

print()

a6q3_input = [1,2,3,2,5,0,7,9,7]
print("Q3. Input: number of occurences in a list of number 7.")
print("    Output: Number of occurrences : ", dict(Counter(a6q3_input))[7])

print()

a6q4_input = [2,25,63,12,48,65,48,49,23]
print("Q4. Input : Sort the array using bubble sort.")
a6q4_input.sort()
print("    Output : ", a6q4_input)

print()

import numpy as np
print("Q5. Input : Manipulating 2D matrices : ")
a6q5_input = np.zeros((3,3))
print('    Output : initial array : ')
print(a6q5_input)
print('\nUpdated Array 1: ')
print(np.where(a6q5_input == 0, 1, a6q5_input))
print('\nUpdated Array 0: ')
print(np.where(a6q5_input == 1, 0, a6q5_input))

print()

a6q6_input_a = np.array([[1,2],[3,4]])
a6q6_input_b = np.array([[1, 2, 3], [4, 9, 6], [7, 8, 9]])
print("Q6. Input : 2D array's inverse : ")
print(a6q6_input_a)
print("Inverse of the said matrix:", np.linalg.inv(a6q6_input_a))

print("Original matrix:")
print(a6q6_input_b)
print("Inverse of the said matrix:", np.linalg.inv(a6q6_input_b))

Q1. Input: Looping through each elements in the array : 
    Output: 
1
3
5
7
9
1
3
5

Q2. Input: Reverse a list.
    Output: Reversed array -  [55, 414, 323, 2, 11]

Q3. Input: number of occurences in a list of number 7.
    Output: Number of occurrences :  2

Q4. Input : Sort the array using bubble sort.
    Output :  [2, 12, 23, 25, 48, 48, 49, 63, 65]

Q5. Input : Manipulating 2D matrices : 
    Output : initial array : 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Updated Array 1: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Updated Array 0: 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Q6. Input : 2D array's inverse : 
[[1 2]
 [3 4]]
Inverse of the said matrix: [[-2.   1. ]
 [ 1.5 -0.5]]
Original matrix:
[[1 2 3]
 [4 9 6]
 [7 8 9]]
Inverse of the said matrix: [[-0.6875     -0.125       0.3125    ]
 [-0.125       0.25       -0.125     ]
 [ 0.64583333 -0.125      -0.02083333]]
